### ISSUE TITLE
saveLocation doesn't seem to work anymore

### ISSUE THREAD

**Issue by LeoFau** [robotemi/sdk#223]
Hi,

I have written an App in which I have included the function of saving the current location by writing it down in an editText and than saving it by pushing a button.

This had already worked before, but it does not work anymore and crashes at the line of the boolean result...

```
btnNewLocation = (Button) findViewById(R.id.btnNewLocation);
        btnNewLocation.setOnClickListener(new View.OnClickListener(){
            @Override
            public void onClick (View v) {
                    String location = etSaveLocation.getText().toString().toLowerCase();
                    boolean result = robot.saveLocation(location);
                    if (result) {
                        robot.speak(TtsRequest.create("Ich habe den Ort " + location + " gespeichert.", true));
                    } else {
                        robot.speak(TtsRequest.create("Speichern von Ort " + location + " fehlgeschlagen.", true));
                    }
                    hideKeyboard(v);
                }
        });
```

The permissions are also added in the manifest in the application part:

```
<meta-data
            android:name="@string/metadata_permissions"
            android:value="com.robotemi.permission.settings, com.robotemi.permission.face_recognition, com.robotemi.permission.map" />
```

What could be the reason for this?

**Comment by lcgao** [comment]
Please provide the crash log here.

**Comment by LeoFau** [comment]
Hi,

I get the following Exception:
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.temiapp, PID: 4847
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.robotemi.sdk.Robot.saveLocation(java.lang.String)' on a null object reference
        at com.example.temiapp.RegionActivity$2.onClick(RegionActivity.java:56)
        at android.view.View.performClick(View.java:5204)
        at android.view.View$PerformClick.run(View.java:21177)
        at android.os.Handler.handleCallback(Handler.java:743)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:772)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:662)
```
I did check and let the App print the String in a Toast to see if it actually does not take the entered text, but that worked fine. I also tried it without the "toLowerCase()" because I thought, maybe that might be a problem, but that didn't change anything.

**Comment by lcgao** [comment]
You should make sure the variable `robot` is not null before using it, anyway you can use `Robot.getInstance()` instead of `robot` variable, like `Robot.getInstance().saveLocation()`, `Robot.getInstance().speak()`.
